### ISSUE TITLE
无法导入EmojiOptions.source

### ISSUE THREAD

**Issue by ABKQPO** [Agnes4m/nonebot_plugin_pjsk#22]
已经从原仓库下载了全部文件，包括图片、字体、characters.json

```
01-30 15:08:15 [ERROR] nonebot_plugin_pjsk | Error occurred while getting character list
TypeError: 'builtin_function_or_method' object cannot be converted to 'EmojiSource'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 19, in <module>
  File "D:\NoneBot\nb\.venv\lib\site-packages\nonebot\__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "D:\NoneBot\nb\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 189, in run
    uvicorn.run(
  File "D:\NoneBot\nb\.venv\lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "D:\NoneBot\nb\.venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\NoneBot\nb\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
  File "D:\NoneBot\nb\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\NoneBot\nb\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 846, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\NoneBot\nb\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 821, in simple_run
    await handler(
  File "D:\NoneBot\nb\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "D:\NoneBot\nb\.venv\lib\site-packages\nonebot_plugin_pjsk\__main__.py", line 183, in _
    image = await get_all_characters()
  File "D:\NoneBot\nb\.venv\lib\site-packages\nonebot_plugin_pjsk\draw.py", line 371, in get_all_characters
    return await use_image_cache(render_all_characters, "all_characters")()
  File "D:\NoneBot\nb\.venv\lib\site-packages\nonebot_plugin_pjsk\draw.py", line 342, in wrapper
    raw_image = await func(*args, **kwargs)
  File "D:\NoneBot\nb\.venv\lib\site-packages\nonebot_plugin_pjsk\draw.py", line 365, in render_all_characters
    return await render_summary_from_tasks(
  File "D:\NoneBot\nb\.venv\lib\site-packages\nonebot_plugin_pjsk\draw.py", line 288, in render_summary_from_tasks
    await asyncio.gather(*tasks),
  File "D:\NoneBot\nb\.venv\lib\site-packages\nonebot_plugin_pjsk\draw.py", line 235, in draw_sticker
    text_img = await render_text(
  File "D:\NoneBot\nb\.venv\lib\site-packages\nonebot_plugin_pjsk\draw.py", line 102, in render_text
    font = Font(
TypeError: argument 'emoji_options': failed to extract field EmojiOptions.source

```

**Comment by lgc2333** [comment]
尝试安装 `imagetext-py==2.1.3`

**Comment by lgc2333** [comment]
可能是库有变动，等我找时间修

**Comment by ABKQPO** [comment]
可以使用了，感谢

**Comment by lgc2333** [comment]
0.3.0 换用了 htmlrender 渲染表情
